remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# Site Settings
title: "AGNES EKPO"
name: "Agnes Ekpo"
description: "Personal website showcasing my data science projects and skills"
url: "https://agnesekpo.com"
repository: "TheAEkpo/agnesekpo.com"

# Site Author
author:
  avatar: "/assets/images/profile-photo.jpg"
  bio: "Data Scientist passionate about solving problems with data"
  
# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: splash
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: splash
      author_profile: false

# Include pages
include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
# Disable feed link from being added
feed:
  path: ""
  
# Comment page
comments:
  provider: "giscus"
  giscus:
    repo: "TheAEkpo/agnesekpo.com"       
    repo_id: "R_kgDOOUrMew"             
    category: "Announcements"           
    category_id: "DIC_kwDOOUrMe84Co35-" 
    mapping: "pathname"                 
    reactions_enabled: "1"              
    emit_metadata: "0"                 
    input_position: "top"              
    theme: "preferred_color_scheme"     
    lang: "en"                          
    loading: "lazy"                     
    crossorigin: "anonymous"            

